---
- name: Install the latest version of tmux.
  package:
    name: tmux
    state: latest

- name: Install Forever
  npm:
    name: forever
    global: yes

- name: Download c9/core
  git:
    repo: "git://github.com/c9/core.git"
    dest: "{{ workspace }}/c9sdk"

- name: Install cloud9 dependencies.
  shell: >
    scripts/install-sdk.sh
  args:
    chdir: "{{ workspace }}/c9sdk"
    creates: "{{ workspace }}/c9sdk/home"

- name: Copy cloud9 init script into place.
  template:
    src: cloud9.init.j2
    dest: /etc/init.d/cloud9
    owner: root
    group: root
    mode: 0755

- name: Ensure cloud9 is enabled and will start on boot.
  service:
    name: cloud9
    state: started
    enabled: yes
